-- Meridian Engine — Publications & Archived Datasets Schema
-- Run this in the Supabase SQL Editor (Dashboard > SQL Editor > New Query)
-- Requires: auth.users, user_roles table, is_admin() function (from admin.sql)

-- ═══════════════════════════════════════════════════════════
-- 1. TABLES
-- ═══════════════════════════════════════════════════════════

-- ── Publications ──
create table publications (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users not null,
  title text not null,
  authors jsonb not null,  -- [{name, affiliation, email, orcid}]
  collaborators jsonb,     -- [{name, type, country}]
  abstract text not null,
  keywords text[],
  category text not null check (category in (
    'Field Study', 'Technical Report', 'Thesis/Dissertation', 'Review',
    'Dataset Description', 'Monitoring Report', 'Methodology',
    'Policy Brief', 'Preprint', 'Other'
  )),
  location_region text,
  location_lat float8,
  location_lng float8,
  species_studied text[],
  time_frame_start date,
  time_frame_end date,
  pdf_url text,
  word_count integer,
  sections_detected jsonb,  -- {abstract, introduction, methods, results, discussion, conclusion, references}
  reference_count integer,
  quality_checks jsonb,     -- stores all automated check results
  meridian_id text unique,  -- format ME-YYYY-NNNN, auto-generated by trigger
  status text not null default 'pending_review' check (status in (
    'draft', 'pending_review', 'published', 'flagged', 'removed'
  )),
  endorsement_count integer not null default 0,
  flag_count integer not null default 0,
  is_trusted_author boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  linked_dataset_ids uuid[]
);

-- ── Publication Comments ──
create table publication_comments (
  id uuid default gen_random_uuid() primary key,
  publication_id uuid references publications on delete cascade not null,
  user_id uuid references auth.users not null,
  comment_text text not null,
  created_at timestamptz not null default now()
);

-- ── Publication Flags ──
create table publication_flags (
  id uuid default gen_random_uuid() primary key,
  publication_id uuid references publications not null,
  user_id uuid references auth.users not null,
  reason text not null check (reason in (
    'plagiarism', 'misleading_data', 'insufficient_methods',
    'factual_errors', 'spam', 'other'
  )),
  description text,
  created_at timestamptz not null default now()
);

-- ── Publication Endorsements ──
create table publication_endorsements (
  id uuid default gen_random_uuid() primary key,
  publication_id uuid references publications on delete cascade not null,
  user_id uuid references auth.users not null,
  created_at timestamptz not null default now(),
  unique (publication_id, user_id)
);

-- ── Trusted Authors ──
create table trusted_authors (
  user_id uuid references auth.users primary key,
  approved_by uuid references auth.users,
  approved_at timestamptz not null default now()
);

-- ── Archived Datasets ──
create table archived_datasets (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users not null,
  title text not null,
  description text not null,
  authors jsonb,  -- [{name, affiliation, email, orcid}]
  data_type text not null check (data_type in (
    'Catch Data', 'Survey Data', 'Environmental Monitoring',
    'Genetic/Genomic', 'Acoustic/Telemetry', 'Photo/Video Transect',
    'Water Quality', 'Population Census', 'Tagging/Recapture',
    'Socioeconomic', 'Other'
  )),
  file_format text check (file_format in (
    'CSV', 'XLSX', 'JSON', 'NetCDF', 'R Data', 'ZIP', 'Other'
  )),
  file_url text,
  file_size_bytes bigint,
  region text,
  location_lat float8,
  location_lng float8,
  species text[],
  time_frame_start date,
  time_frame_end date,
  variables_included text[],  -- e.g. SST, Length, Weight, Depth, Salinity
  collection_method text,
  sample_size integer,
  license text check (license in ('CC-BY', 'CC-BY-NC', 'CC-BY-SA', 'CC0', 'Custom')),
  linked_publication_id uuid references publications,
  meridian_data_id text unique,  -- format MD-YYYY-NNNN, auto-generated by trigger
  download_count integer not null default 0,
  created_at timestamptz not null default now(),
  status text not null default 'published' check (status in (
    'published', 'draft', 'removed'
  ))
);


-- ═══════════════════════════════════════════════════════════
-- 2. STORAGE BUCKETS
-- ═══════════════════════════════════════════════════════════

insert into storage.buckets (id, name, public, file_size_limit)
values
  ('publication-pdfs', 'publication-pdfs', true, 52428800),      -- 50 MB
  ('archived-datasets', 'archived-datasets', true, 209715200)   -- 200 MB
on conflict (id) do nothing;

-- Storage policies: public read, authenticated upload
create policy "Public read publication PDFs"
  on storage.objects for select
  using (bucket_id = 'publication-pdfs');

create policy "Authenticated upload publication PDFs"
  on storage.objects for insert
  with check (bucket_id = 'publication-pdfs' and auth.role() = 'authenticated');

create policy "Users delete own publication PDFs"
  on storage.objects for delete
  using (bucket_id = 'publication-pdfs' and auth.uid()::text = (storage.foldername(name))[1]);

create policy "Public read archived datasets"
  on storage.objects for select
  using (bucket_id = 'archived-datasets');

create policy "Authenticated upload archived datasets"
  on storage.objects for insert
  with check (bucket_id = 'archived-datasets' and auth.role() = 'authenticated');

create policy "Users delete own archived datasets"
  on storage.objects for delete
  using (bucket_id = 'archived-datasets' and auth.uid()::text = (storage.foldername(name))[1]);


-- ═══════════════════════════════════════════════════════════
-- 3. ROW LEVEL SECURITY
-- ═══════════════════════════════════════════════════════════

alter table publications enable row level security;
alter table publication_comments enable row level security;
alter table publication_flags enable row level security;
alter table publication_endorsements enable row level security;
alter table trusted_authors enable row level security;
alter table archived_datasets enable row level security;

-- ── Publications RLS ──

-- Anyone can read published publications
create policy "Anyone can read published publications"
  on publications for select
  using (status = 'published' or auth.uid() = user_id or is_admin());

-- Authenticated users can create publications
create policy "Authenticated users can create publications"
  on publications for insert
  with check (auth.uid() = user_id);

-- Users can update their own draft/pending publications; admins can update any
create policy "Users update own draft/pending; admins update any"
  on publications for update
  using (
    (auth.uid() = user_id and status in ('draft', 'pending_review'))
    or is_admin()
  );

-- Users can delete their own draft/pending publications; admins can delete any
create policy "Users delete own draft/pending; admins delete any"
  on publications for delete
  using (
    (auth.uid() = user_id and status in ('draft', 'pending_review'))
    or is_admin()
  );

-- ── Publication Comments RLS ──

create policy "Anyone can read comments on published pubs"
  on publication_comments for select
  using (
    exists (
      select 1 from publications p
      where p.id = publication_id and (p.status = 'published' or p.user_id = auth.uid())
    ) or is_admin()
  );

create policy "Authenticated users can comment"
  on publication_comments for insert
  with check (auth.uid() = user_id);

create policy "Users delete own comments; admins delete any"
  on publication_comments for delete
  using (auth.uid() = user_id or is_admin());

-- ── Publication Flags RLS ──

create policy "Users can read own flags; admins read all"
  on publication_flags for select
  using (auth.uid() = user_id or is_admin());

create policy "Authenticated users can flag"
  on publication_flags for insert
  with check (auth.uid() = user_id);

create policy "Admins can delete flags"
  on publication_flags for delete
  using (is_admin());

-- ── Publication Endorsements RLS ──

create policy "Anyone can read endorsements"
  on publication_endorsements for select
  using (true);

create policy "Authenticated users can endorse"
  on publication_endorsements for insert
  with check (auth.uid() = user_id);

create policy "Users can remove own endorsement"
  on publication_endorsements for delete
  using (auth.uid() = user_id);

-- ── Trusted Authors RLS ──

create policy "Anyone can read trusted authors"
  on trusted_authors for select
  using (true);

create policy "Admins manage trusted authors"
  on trusted_authors for insert
  with check (is_admin());

create policy "Admins remove trusted authors"
  on trusted_authors for delete
  using (is_admin());

-- ── Archived Datasets RLS ──

create policy "Anyone can read published datasets"
  on archived_datasets for select
  using (status = 'published' or auth.uid() = user_id or is_admin());

create policy "Authenticated users can create datasets"
  on archived_datasets for insert
  with check (auth.uid() = user_id);

create policy "Users update own datasets; admins update any"
  on archived_datasets for update
  using (auth.uid() = user_id or is_admin());

create policy "Users delete own datasets; admins delete any"
  on archived_datasets for delete
  using (auth.uid() = user_id or is_admin());


-- ═══════════════════════════════════════════════════════════
-- 4. DATABASE FUNCTIONS & TRIGGERS
-- ═══════════════════════════════════════════════════════════

-- ── generate_meridian_id() — auto-assigns ME-YYYY-NNNN on publication insert ──
create or replace function generate_meridian_id()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  current_year text;
  next_seq int;
begin
  current_year := to_char(now(), 'YYYY');

  select coalesce(max(
    cast(substring(meridian_id from 'ME-' || current_year || '-(\d+)') as int)
  ), 0) + 1
  into next_seq
  from publications
  where meridian_id like 'ME-' || current_year || '-%';

  new.meridian_id := 'ME-' || current_year || '-' || lpad(next_seq::text, 4, '0');
  return new;
end;
$$;

create trigger trg_generate_meridian_id
  before insert on publications
  for each row
  when (new.meridian_id is null)
  execute function generate_meridian_id();

-- ── generate_data_id() — auto-assigns MD-YYYY-NNNN on dataset insert ──
create or replace function generate_data_id()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  current_year text;
  next_seq int;
begin
  current_year := to_char(now(), 'YYYY');

  select coalesce(max(
    cast(substring(meridian_data_id from 'MD-' || current_year || '-(\d+)') as int)
  ), 0) + 1
  into next_seq
  from archived_datasets
  where meridian_data_id like 'MD-' || current_year || '-%';

  new.meridian_data_id := 'MD-' || current_year || '-' || lpad(next_seq::text, 4, '0');
  return new;
end;
$$;

create trigger trg_generate_data_id
  before insert on archived_datasets
  for each row
  when (new.meridian_data_id is null)
  execute function generate_data_id();

-- ── increment_endorsement() — inserts endorsement + increments count ──
create or replace function increment_endorsement(pub_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  -- Insert endorsement (unique constraint prevents duplicates)
  insert into publication_endorsements (publication_id, user_id)
  values (pub_id, auth.uid());

  -- Increment counter on the publication
  update publications
  set endorsement_count = endorsement_count + 1
  where id = pub_id;
end;
$$;

-- ── remove_endorsement() — removes endorsement + decrements count ──
create or replace function remove_endorsement(pub_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  delete from publication_endorsements
  where publication_id = pub_id and user_id = auth.uid();

  if found then
    update publications
    set endorsement_count = greatest(0, endorsement_count - 1)
    where id = pub_id;
  end if;
end;
$$;

-- ── increment_download() — increments download_count on archived_datasets ──
create or replace function increment_download(dataset_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update archived_datasets
  set download_count = download_count + 1
  where id = dataset_id;
end;
$$;

-- ── Auto-update updated_at on publications ──
create or replace function update_publications_timestamp()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

create trigger trg_publications_updated_at
  before update on publications
  for each row
  execute function update_publications_timestamp();

-- ── Auto-set is_trusted_author on publication insert ──
create or replace function set_trusted_author_flag()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  new.is_trusted_author := exists (
    select 1 from trusted_authors where user_id = new.user_id
  );
  return new;
end;
$$;

create trigger trg_set_trusted_author
  before insert on publications
  for each row
  execute function set_trusted_author_flag();

-- ── Auto-update flag_count when a flag is inserted ──
create or replace function update_flag_count()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  update publications
  set flag_count = (
    select count(*) from publication_flags where publication_id = new.publication_id
  )
  where id = new.publication_id;
  return new;
end;
$$;

create trigger trg_update_flag_count
  after insert on publication_flags
  for each row
  execute function update_flag_count();


-- ═══════════════════════════════════════════════════════════
-- 5. INDEXES
-- ═══════════════════════════════════════════════════════════

create index idx_publications_status on publications(status);
create index idx_publications_meridian_id on publications(meridian_id);
create index idx_publications_user_id on publications(user_id);
create index idx_publications_category on publications(category);
create index idx_publications_created_at on publications(created_at desc);

create index idx_pub_comments_publication on publication_comments(publication_id);
create index idx_pub_flags_publication on publication_flags(publication_id);
create index idx_pub_endorsements_publication on publication_endorsements(publication_id);

create index idx_archived_datasets_region on archived_datasets(region);
create index idx_archived_datasets_species on archived_datasets using gin(species);
create index idx_archived_datasets_data_type on archived_datasets(data_type);
create index idx_archived_datasets_meridian_data_id on archived_datasets(meridian_data_id);
create index idx_archived_datasets_user_id on archived_datasets(user_id);
create index idx_archived_datasets_created_at on archived_datasets(created_at desc);
